---
title: "Image Segmentation - Project Proposal"
author: "Radhai"
date: "April 1, 2018"
output: html_document
---


##Project Goal 

The goal of segmentation is to simplify and/or change the representation of an image into something that is more meaningful and easier to analyze.

Segmentation is generally the first stage in any attempt to analyze or interpret an image automatically. Segmentation bridges the gap between low-level image processing and high-level image processing.

This has application in various areas:
+Industrial inspection
+Optical character recognition (OCR) 
+Tracking of objects in a sequence of images 
+Classification of terrains visible in satellite images. 
+Detection and measurement of bone, tissue, etc., in medical images.


##Dataset
I downloaded the data available in the following link for machine learning purpose:
[Image Segmentation](https://archive.ics.uci.edu/ml/datasets/Image+Segmentation)

##My brief approach in classifying this data:
1. Create a numeric field to assign a numeric value to each class, which is currently a character field.
2. Use the R functions like: summary, cor, plot, lm to understand the relationship between different columns and the Class variable.
3. Create a model that will classify the data into one of the expected seven classes.
4. Test the model on the test data.





